#!/usr/bin/env bash

#
# Inner Plugin:  periodic post heartbeat.
#

BASE_DIR="/usr/local/eminfo"
if [ -f ${BASE_DIR}/bin/include -a -s ${BASE_DIR}/bin/include ]; then
        source ${BASE_DIR}/bin/include 2>&1
        rc=$?
        [ "$rc" != "0" ] && {
                echo "load include file failed with status $rc"
                exit 1
        }   
else
        echo "${BASE_DIR}/bin/include not exist or empty. exit" 
        exit 1
fi

# Return Codes
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_NOOP=4

# Set Default
EXIT_STATUS=0
LEVEL=          ### { ok | warn | crit | unknown }
TYPE=           ### { str| file }
CONTENT=        ### { strings | /path/to/result.file }

# check function here
check() {
  local info=
  local timestamp=$(date +%s)
  local info="${timestamp} | iamalive"
  info="{ok}:{str}:{${info}}"
  ${POSTLOG_SH} -f "eminfo_iam_alive" -s "IAMALIVE" -i "${info}" -h "Nothing to do" 2>&1
  if [ "$?" == "0" ]; then
	EXIT_STATUS="${STATE_OK}"
	LEVEL="ok"
	TYPE="str"
	CONTENT=" post eminfo heartbeat succeed | post eminfo heartbeat succeed "
  else
	EXIT_STATUS="${STATE_WARNING}"
	LEVEL="warn"
	TYPE="str"
	CONTENT=" post eminfo heartbeat failed | post eminfo heartbeat failed "
  fi
}

check

# output result and return exit status here.
echo "{"${LEVEL}"}:{"${TYPE}"}:{"${CONTENT}"}"  | tr -d '\015\012'
exit ${EXIT_STATUS}  
