#!/usr/bin/env bash

#
# Inner Plugin:  periodic check self.
#

if [ -z "${BASE_DIR}" ]; then
        path=$(cd $(dirname $0) && pwd)
        BASE_DIR=${path%/*}
        BASE_DIR=${BASE_DIR%/*}
        source ${BASE_DIR}/bin/include 2>&-
fi



# Read plugin config value here

# if null or invalid set default.

# check function here
check() {
  local result=

  status=$(/usr/local/eminfo/eminfo status 2>&1); rc=$?
  if [ "${rc}" != "0" ]; then
  	result="eminfo status check return [${rc}] [${status}];"
  else
	result="eminfo status check return [0] OK;"
  fi

  precheck=$(${PRECHECK_SH} 2>&1); rc=$?
  if [ "${rc}" != "0" ]; then
  	result="${result} eminfo precheck return [${rc}] [${precheck}];"
  else
	result="${result} eminfo precheck return [0] OK;"
  fi

  checkconf=$(${CHECKCONF_SH} 2>&1); rc=$?
  if [ "${rc}" != "0" ]; then
  	result="${result} eminfo checkconf return [${rc}] [${checkconf}];"
  else
	result="${result} eminfo checkconf return [0] OK;"
  fi

  echo "${result}" | tr -d '\r\n'
}

check
