#!/usr/bin/env bash

#
# Inner Plugin:  periodic rollback logfiles.
#

BASE_DIR="/usr/local/eminfo"
if [ -f ${BASE_DIR}/bin/include -a -s ${BASE_DIR}/bin/include ]; then
        source ${BASE_DIR}/bin/include 2>&1
        rc=$?
        [ "$rc" != "0" ] && {
                echo "load include file failed with status $rc"
                exit 1
        }   
else
        echo "${BASE_DIR}/bin/include not exist or empty. exit" 
        exit 1
fi

# Return Codes
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_NOOP=4

# Set Default
EXIT_STATUS=0
LEVEL=          ### { ok | warn | crit | unknown }
TYPE=           ### { str| file }
CONTENT=        ### { strings | /path/to/result.file }

# Read plugin config value here
force_size_uplimit=$( read_eminfo_config eminfo_log_rotate force_size_uplimit )

# if null or invalid set default.
[ -z "${force_size_uplimit}" -o ! -z "${force_size_uplimit//[0-9]}" ] && force_size_uplimit=1024

# check function here
check() {
  local result= rollnum=0
  array_logfiles=( 
		${EMINFO_LOG} 
		${INNER_LOG} 
		${PRECHECK_LOG} 
		${POSTLOG_LOG} 
		${TAKESNAP_LOG} 
		${UPDATE_LOG} 
		${SENDMAIL_LOG} 
		${ERRLOG}
		"${LOG_DIR}/sync_user524.log"
		"${LOG_DIR}/sync_userfail.log"
		"${LOG_DIR}/cancle_migrate.log"
		)

  for file in  ${array_logfiles[@]}
  do
	if [ -f "${file}" ]; then

		## 1. check filesize
		local size=$( /usr/bin/du -sm "${file}" 2>&- | awk '{print $1}' )
		if [ -z "${size}"  -o ! -z "${size//[0-9]}" ]; then
			[ "$( echo "${size} >= ${force_size_uplimit}" | bc )" == "1" ] &&  {
				local basefile="${BACK_DIR}/${file##*/}.$(date +%F).${size}M"
				local dstfile="${basefile}"
				local seqnum=0
				while [ -f "${dstfile}" ]
				do
					((seqnum++))
					dstfile="${basefile}_${seqnum}"
				done

		    		mv  "${file}" "${dstfile}" 2>&-
				((rollnum++))
		    		result="${result} [${file}] filesize:[${size}M >= ${force_size_uplimit}M] ### rollback:[${dstfile}] ### ### "
		    		continue
			}
		fi

		## 2. check current time : the begining of newday or not
		local day_start=$(date -d "" +%s)     ### the begining of today
		local time_long=$( conv_time2sec "$(get_frequency eminfo_log_rotate)" )    ### timelong of this plugin
		local end_time=$(( ${day_start} + ${time_long} ))
		local now_time=$(date +%s)		### nower time
		[ "$(echo "${now_time} < ${end_time}" | bc 2>&-)" == "1" ] && {
			local basefile="${BACK_DIR}/${file##*/}.$(date -d "-1day" +%F)"
			local dstfile="${basefile}"
			local seqnum=0
			while [ -f "${dstfile}" ]
			do
				((seqnum++))
				dstfile="${basefile}_${seqnum}"
			done	
			
			mv "${file}" "${dstfile}" 2>&-
			((rollnum++))
			result="${result} [${file}] newday:[$(date +%F_%T)] ### rollback:[${dstfile}] ### ###"
			continue
		}

		## 3. check head and tail logitem is the same day or not?
		local head_ts=$( head -n1 "${file}" | awk '{print $1}' )
		local tail_ts=$( tail -n1 "${file}" | awk '{print $1}' )
		[ -z "${head_ts}" -o ! -z "${head_ts//[0-9]}" -o -z "${tail_ts}" -o ! -z "${tail_ts//[0-9]}" ] || {
			head_day=$( date -d "1970-01-01 UTC ${head_ts} seconds" +%F)
			tail_day=$( date -d "1970-01-01 UTC ${tail_ts} seconds" +%F)
			[ "${head_day}" != "${tail_day}" ] && {
				local basefile="${BACK_DIR}/${file##*/}.${head_day}"
				local dstfile="${basefile}"
				local seqnum=0
				while [ -f "${dstfile}" ]
				do
					((seqnum++))
					dstfile="${basefile}_${seqnum}"
				done

			    	mv "${file}" "${dstfile}" 2>&-
				((rollnum++))
			    	result="${result} [${file}] newlog:[${tail_day} <> ${head_day}] ### rollback:[${dstfile}] ### ###"
			    	continue
			}
		}

		## 4. check head logitem is today or not ?
		local head_ts=$( head -n1 "${file}" | awk '{print $1}' )
		[ -z "${head_ts}" -o ! -z "${head_ts//[0-9]}" ] || {
			head_day=$( date -d "1970-01-01 UTC ${head_ts} seconds" +%F)
			today=$(date +%F)
			[ "${head_day}" != "${today}" ] && {
				local basefile="${BACK_DIR}/${file##*/}.${head_day}"
				local dstfile="${basefile}"
				local seqnum=0
				while [ -f "${dstfile}" ]
				do
					((seqnum++))
					dstfile="${basefile}_${seqnum}"
				done
	
				mv "${file}" "${dstfile}" 2>&-
				((rollnum++))
				result="${result} [${file}] headday:[${head_day} <> today] ### rollback:[${dstfile}] ### ###"
				continue
			}
		}
	fi
  done
  
  [ -z "${result}" ] && {
  	EXIT_STATUS="${STATE_OK}"
  	LEVEL="ok"
	TYPE="str"
	CONTENT="Nothing to do | No files to be processed"
  } || {
	EXIT_STATUS="${STATE_OK}"
	LEVEL="ok"
	TYPE="str"
	CONTENT="RollBack finished | ${rollnum} files rolled back | ${result}"
  }

}

check

# output result and return exit status here.
echo "{"${LEVEL}"}:{"${TYPE}"}:{"${CONTENT}"}"  | tr -d '\015\012'
exit ${EXIT_STATUS}
