#!/usr/bin/env bash


if [ -z "${BASE_DIR}" ]; then
	path=$(cd $(dirname $0) && pwd)  
	BASE_DIR=${path%/*}
	source ${BASE_DIR}/bin/include 2>&-
fi




# Return Codes
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_NOOP=4

# Set Default
EXIT_STATUS=0
LEVEL=    	### { ok | warn | crit | unknown }
TYPE=   	### { str| file }
CONTENT=        ### { strings | /path/to/result.file }

# Read plugin config value here
uplimit=$( read_eminfo_config check_sysload uplimit )

# if null return STATE_UNKNOWN.

# if null or invalid set default.
[ -z "${uplimit}" -o ! -z "${uplimit//[0-9]}" ] && uplimit=10

# check function here
check(){
  local loadave=$( cut -d" " -f1 /proc/loadavg 2>&1 )
  [ -z "${loadave}" -o ! -z "${loadave//[0-9.]}" ] && {
        EXIT_STATUS=${STATE_UNKNOWN};
        LEVEL="unknown";
        TYPE="str";
        CONTENT="Retuen is not numberic: ["${loadave}"]"
        return
  }
  if [ "$(echo  "${loadave} >= ${uplimit}" | bc 2>&-)" == "1" ]; then
	EXIT_STATUS=${STATE_WARNING};
	LEVEL="warn";
	TYPE="str";
	CONTENT="System Load Check CRITICAL | Load Average: [${loadave}] >= UpLimit: [${uplimit}] "
  else
	EXIT_STATUS=${STATE_OK};
	LEVEL="ok";
	TYPE="str";
	CONTENT="System Load Check OK | load average: [${loadave}] <= UpLimit: [${uplimit}] "
  fi
}

check


# output result and return exit status here.
echo "{"${LEVEL}"}:{"${TYPE}"}:{"${CONTENT}"}"  | tr -d '\015\012'
exit ${EXIT_STATUS}
