#!/usr/bin/env bash


if [ -z "${BASE_DIR}" ]; then
	path=$(cd $(dirname $0) && pwd)  
	BASE_DIR=${path%/*}
	source ${BASE_DIR}/bin/include 2>&-
fi




# Return Codes
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_NOOP=4

# Set Default
EXIT_STATUS=0
LEVEL=    	### { ok | warn | crit | unknown }
TYPE=    	### { str| file }
CONTENT=        ### { strings | /path/to/result.file }

# Read plugin config value here
uplimit=$( read_eminfo_config check_memory uplimit )

# if null return STATE_UNKNOWN.

# if null or invalid set default.
[ -z "${uplimit}" -o ! -z "${uplimit//[0-9]}" ] && uplimit=90

# check function here
check(){

  [ -f "/proc/meminfo" -a -r "/proc/meminfo" ] || {
	EXIT_STATUS=${STATE_UNKNOWN};
	LEVEL="unknown";
	TYPE="str";
	CONTENT="[/proc/meminfo] not prepared.";
	return
  }

  local total=$(awk '/^MemTotal:/ {print $2}' /proc/meminfo 2>&-)
  local free=$(awk '/^MemFree:/ {print $2}' /proc/meminfo 2>&-)
  [ -z "${total}" -o ! -z "${total//[0-9]}" -o -z "${free}" -o ! -z "${free//[0-9]}" ] && {
	EXIT_STATUS=${STATE_UNKNOWN};
	LEVEL="unknown";
	TYPE="str";
	CONTENT="total=[${total}] or free=[${free}] is not numberic.";
	return
  }

  local percent=$( echo "scale=3; 100 * (1 - ${free}/${total})" | bc 2>&- )
  [ -z "${percent}" -o ! -z "${percent//[0-9.]}" ] && {
	EXIT_STATUS=${STATE_UNKNOWN};
        LEVEL="unknown";
        TYPE="str";
        CONTENT="Retuen is not numberic: ["${percent}"]";
	return 
  }

  if [ "$(echo  "${percent} >= ${uplimit}" | bc 2>&-)" == "1" ]; then
	EXIT_STATUS=${STATE_CRITICAL};
	LEVEL="crit";
	TYPE="str";
	CONTENT="Memory Usage Check CRITICAL | Memory Usage: [${percent}]% | Memory Usage: [${percent}%] >= UpLimit: [${uplimit}%] ### total=[$((${total}/1024))]M  free=[$((${free}/1024))]M "
  else
	EXIT_STATUS=${STATE_OK};
	LEVEL="ok";
	TYPE="str";
	CONTENT="Memory Usage Check OK | Memory Usage: [${percent}%] <= UpLimit: [${uplimit}%] ### total=[$((${total}/1024))]M  free=[$((${free}/1024))]M "
  fi
}

check

# output result and return exit status here.
echo "{"${LEVEL}"}:{"${TYPE}"}:{"${CONTENT}"}"  | tr -d '\015\012'
exit ${EXIT_STATUS}
