#!/usr/bin/env bash

array=( 10 19 87 -19 2 0 7 943 61 45 37 521 )


## begin
echo "${array[*]}"
len=${#array[*]}
for((i=0;i<${len};i++))  ### only control times
do
	for((x=0;x<${len};x++))
	do
		x2=$(($x+1))
		[ "$(echo "${array[${x}]} > ${array[${x2}]}" | bc 2>&-)" == "1" ] && {
			echo "change ${array[${x}]} ${array[${x2}]}"
			tmp=${array[${x2}]}
			array[${x2}]=${array[${x}]}
			array[${x}]=${tmp}
		} || {
			# echo "skip ${array[${x}]} ${array[${x2}]}"
			:
		}
	done
done
echo "${array[*]}"
