#!/usr/bin/env bash

regex="1([358][0-9]|45|47)[0-9]{4,8}" 
mobnum=$(echo "$1"|egrep -o "${regex}")
if [ -z "${mobnum}" -o ! -z "${mobnum//[0-9]}" ]; then 
    echo "input mobile number invalid: [${1}]"
    echo "Example: ./${0##*/} 13436681090"
else 
    /usr/bin/curl -s "http://wap.ip138.com/sim_search.asp?mobile=${mobnum}"| sed -ne '/'${mobnum}'<br\/>/,+3p' | sed -e 's#<br/>##g; s#<div>##g'
fi 
